"""Persist a document generated by the agent.

Takes an already-validated DocumentSpec, renders it to the requested format,
*validates the rendered bytes independently* (so we never register a broken
file), writes it to the uploads volume, creates the Document row scoped to the
authenticated user and indexes it (best effort) so the new document is
searchable and readable exactly like an uploaded one.

Ownership is never taken from tool arguments: ``user_id`` is passed by the
caller from the authenticated request context.

Failures are reported via typed errors so the agent can return a precise
``error_type`` to the API instead of a generic message:
  * ``RendererError``             - render or post-render validation failed.
  * ``DocumentSaveError``         - the file could not be written to storage.
  * ``DocumentRegistrationError`` - the DB row could not be committed.
"""

import logging
import re

from app.models.document import Document
from app.schemas.document_spec import DocumentSpec
from app.services.document_renderer import render_document, spec_to_text
from app.services.document_validation import validate_document_bytes
from app.services.documents import persist_file
from app.services.errors import (
    DocumentError,
    DocumentRegistrationError,
    RendererError,
)
from app.services.indexing import index_document

logger = logging.getLogger("app.generation")

_DEFAULT_TITLE = "document"


def generate_document(
    spec: DocumentSpec,
    output_format: str,
    user_id: int,
    *,
    chat_id: int | None = None,
    source_file_id: int | None = None,
) -> Document:
    """Render, validate, persist and index a generated document.

    Returns the ``Document`` row. Raises a typed error on any failure. The
    rendered bytes are written through the shared ``persist_file`` helper so
    generated files reuse the exact same storage, ownership and indexing path
    as uploads (and as edited files).
    """
    # 1) Render (the renderer raises RendererError on bad input).
    try:
        content_bytes = render_document(spec, output_format)
    except RendererError:
        raise
    except Exception as exc:  # pragma: no cover - renderer bug surface
        raise RendererError(f"render failed: {exc}") from exc

    # 2) Validate the rendered bytes independently before we trust them.
    validate_document_bytes(content_bytes, output_format, spec)

    original_filename = _safe_filename(spec.title, output_format)
    if output_format in ("md", "txt"):
        content_text = content_bytes.decode("utf-8", errors="replace").strip() or spec.title
    else:
        content_text = spec_to_text(spec) or spec.title

    from app.database.session import SessionLocal

    db = SessionLocal()
    try:
        document = persist_file(
            content_bytes,
            output_format,
            user_id,
            db,
            original_filename=original_filename,
            content_text=content_text,
            source_file_id=source_file_id,
            chat_id=chat_id,
        )
    except DocumentError:
        db.rollback()
        raise
    except Exception as exc:
        db.rollback()
        raise DocumentRegistrationError(
            f"could not register document: {exc}"
        ) from exc
    finally:
        db.close()

    # Indexing must not break creation: the row is already committed, so
    # failures here are logged and reported separately (mirrors uploads).
    try:
        index_document(document)
    except Exception:
        logger.exception("Indexing failed for generated document %s", document.id)

    return document


def _safe_filename(title: str, output_format: str) -> str:
    """Build a filesystem-safe display name from the spec title."""
    cleaned = re.sub(r"[^\w\s()\-_.,]", "_", title or _DEFAULT_TITLE, flags=re.UNICODE)
    cleaned = " ".join(cleaned.split()).strip(" ._")[:80]
    cleaned = cleaned or _DEFAULT_TITLE
    return f"{cleaned}.{output_format}"
