"""Persist a document generated by the agent.

Takes an already-validated DocumentSpec, renders it to the requested format,
writes the file to the uploads volume, creates the Document row scoped to the
authenticated user and indexes it (best effort) so the new document is
searchable and readable exactly like an uploaded one.

Ownership is never taken from tool arguments: ``user_id`` is passed by the
caller from the authenticated request context.
"""

import logging
import re
import uuid
from pathlib import Path

from app.core.config import settings
from app.models.document import Document
from app.schemas.document_spec import DocumentSpec
from app.services.document_renderer import render_document, spec_to_text
from app.services.indexing import index_document

logger = logging.getLogger("app.generation")

_DEFAULT_TITLE = "document"


def generate_document(
    spec: DocumentSpec,
    output_format: str,
    user_id: int,
) -> Document:
    """Render, persist and index a generated document. Returns the Document row."""
    content_bytes = render_document(spec, output_format)

    original_filename = _safe_filename(spec.title, output_format)
    stored_name = f"{uuid.uuid4().hex}.{output_format}"

    upload_dir = Path(settings.UPLOAD_DIR)
    upload_dir.mkdir(parents=True, exist_ok=True)
    filepath = upload_dir / stored_name
    filepath.write_bytes(content_bytes)

    from app.database.session import SessionLocal

    db = SessionLocal()
    try:
        document = Document(
            user_id=user_id,
            filename=stored_name,
            original_filename=original_filename,
            file_type=output_format,
            file_size=len(content_bytes),
            filepath=str(filepath),
            content=spec_to_text(spec) or spec.title,
        )
        db.add(document)
        db.commit()
        db.refresh(document)
    finally:
        db.close()

    # Indexing must not break creation: the row is already committed, so
    # failures here are logged and reported separately (mirrors uploads).
    try:
        index_document(document)
    except Exception:
        logger.exception("Indexing failed for generated document %s", document.id)

    return document


def _safe_filename(title: str, output_format: str) -> str:
    """Build a filesystem-safe display name from the spec title."""
    cleaned = re.sub(r"[^\w\s()\-_.,]", "_", title or _DEFAULT_TITLE, flags=re.UNICODE)
    cleaned = " ".join(cleaned.split()).strip(" ._")[:80]
    cleaned = cleaned or _DEFAULT_TITLE
    return f"{cleaned}.{output_format}"
